SchoolPerformance/SchoolPerformance/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Logging;
using SchoolPerformance.Models;
using SchoolPerformance.Repository;
using StackExchange.Redis;

namespace SchoolPerformance.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            _logger.LogInformation("Request made to view Homepage");
            return View();
        }

        public IActionResult FAQ()
        {
            _logger.LogInformation("Request made to view FAQ page");
            return View();
        }

        public IActionResult About()
        {
            _logger.LogInformation("Request made to view About page");
            return View();
        }

    }
}

SchoolPerformance/SchoolPerformance/Controllers/ScatterplotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SchoolPerformance.Models;
using SchoolPerformance.Repository;
using SchoolPerformance.ViewModels;
using StackExchange.Redis.Extensions.Core.Abstractions;
using SchoolPerformance.Cache;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;

namespace SchoolPerformance.Controllers
{
    public class ScatterplotController : Controller
    {

        private ISchoolPerformanceRepository<SchoolResult> _result;
        private IRedisCache _cache;
        private ILogger<ScatterplotController> _logger;

        public ScatterplotController(ISchoolPerformanceRepository<SchoolResult> result, IRedisCache cache, ILogger<ScatterplotController> logger)
        {
            _result = result;
            _cache = cache;
            _logger = logger;
        }


        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Request made to view Scatterplot page");

            //Check if data is in cache and if so get the data from cache
            IEnumerable<ScatterplotViewModel> schoolLst = await _cache.GetScatterplotData();
            ScatterplotViewModel national = await _cache.GetNationalScatterplotData();

            //if data is not in cache get data from database and save data in cache
            if (schoolLst.Count() == 0)
            {
                _logger.LogInformation("Scatterplot data is being retrieved from the database");

                var result = await _result.Get(r => r.PTFSM6CLA1A != null,
                    r => r.OrderBy(s => s.School.SCHNAME),
                    r => r.School);

                //Converts from list of SchoolResult to List of ScatterplotViewModel
                schoolLst = result.ConvertToScatterplotViewModel();

                await _cache.SaveScatterplotData(schoolLst);
            }

            //if national data is not in cache get data from database and save data in cache
            if(national == null)
            {
                _logger.LogInformation("National Scatterplot data is being retrieved from the database");

                var result = await _result.GetNational(r => r.School);

                national = result.First();

                await _cache.SaveNationalScatterplotData(national);
            }

            var resultViewModel = new ScatterplotListViewModel()
            {
                schoolData = schoolLst,
                nationalData = national,
            };

            return View(resultViewModel);
        }
    }
}

SchoolPerformance/SchoolPerformance/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SchoolPerformance.Models;
using SchoolPerformance.Repository;
using SchoolPerformance.ViewModels;

namespace SchoolPerformance.Controllers
{
    public class SchoolController : Controller
    {
        private ISchoolPerformanceRepository<SchoolResult> _result;
        private ISchoolPerformanceRepository<SchoolContextual> _contextual;
        private ILogger<SchoolController> _logger;


        public SchoolController(ISchoolPerformanceRepository<SchoolResult>result, 
            ISchoolPerformanceRepository<SchoolContextual>contextual, ILogger<SchoolController> logger)
        {
            _result = result;
            _contextual = contextual;
            _logger = logger;
        }

        [HttpPost]
        public IActionResult School(int id)
        {
            //Action method added due to search box
            return RedirectToAction("Index", new { id = id });
        }

        [Route("{id:int}")]
        [Route("/[controller]/{id:int}")]
        public async Task<IActionResult> Index(int id)
        {
            _logger.LogInformation($"Request made to view School page with id: {id}");

            _logger.LogInformation($"Data for {id} is being retrieved from the database");

            //Get the school data for the 2019 academic year
            var schoolResult = await _result
                .GetByUrnOrLAESATB(id, s => s.ACADEMICYEAR == 2019, s => s.School);

            var schoolContextual = await _contextual
                .GetByUrnOrLAESATB(id ,s => s.ACADEMICYEAR == 2019);

            //Return a page letting the user know the id cannot be found
            //If the school id does not exist
            if (schoolResult.Count() == 0)
            {
                return View("SchoolNotFound", id);
            }

            _logger.LogInformation($"National data is being retrieved from the database");

            //Get the national data
            var nationalResult = await _result.GetNational(s => s.ACADEMICYEAR == 2019, s => s.School);
            var nationalContextual = await _contextual.GetNational(s => s.ACADEMICYEAR == 2019);

            //Add School and National data to the SchoolViewModel
            var schoolViewModel = new SchoolViewModel()
            {
                ResultSchool = schoolResult.First(),
                ResultNational = nationalResult.First(),
                ContextualSchool = schoolContextual.First(),
                ContextualNational = nationalContextual.First()
            };

            return View(schoolViewModel);
        }





    }
}

SchoolPerformance/SchoolPerformance/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SchoolPerformance.Cache;
using SchoolPerformance.Models;
using SchoolPerformance.Repository;
using SchoolPerformance.ViewModels;

namespace SchoolPerformance.Controllers
{
    public class TablesController : Controller
    {

        private ISchoolPerformanceRepository<SchoolResult> _result;
        private IRedisCache _cache;
        private ILogger<TablesController> _logger;

        public TablesController(ISchoolPerformanceRepository<SchoolResult> result, IRedisCache cache,
            ILogger<TablesController> logger)
        {
            _result = result;
            _cache = cache;
            _logger = logger;
        }


        public IActionResult Index()
        {
            _logger.LogInformation("Request made to view Results Table All page");

            //Empty TableViewModel returned 
            //to allow me to use HTML display name helpers
            return View(new TableViewModelAll());
        }

        public IActionResult All()
        {
            return RedirectToAction("Index");
        }

        public IActionResult Disadvantaged()
        {
            _logger.LogInformation("Request made to view Results Table Disadvantaged page");

            //Empty TableViewModel returned 
            //to allow me to use HTML display name helpers
            return View(new TableViewModelDisadvantaged());
        }

        [HttpPost]
        public async Task<IActionResult> GetResultsAll()
        {
            _logger.LogInformation("Request made to get JSON object with data for Table All page");

            //Check if data is in cache
            var resultViewModel = await _cache.GetTableDataAll();

            //Get results for all schools from database if data is not in cache
            if (resultViewModel.Count() == 0)
            {
                _logger.LogInformation("Table all data is being retrieved from the database");

                var result = await _result.GetAll(r => r.OrderBy(s => s.School.SCHNAME), r => r.School);

                //Converts from list of SchoolResult to List of TableViewModel
                resultViewModel = result.ConvertToTableViewModelAll();

                //Save list of TableViewModel data to cache
                await _cache.SaveTableDataAll(resultViewModel);
            }

            //Check if data is in cache
            var resultNatViewModel = await _cache.GetNationalTableDataAll();

            //Get the national data from database if data is not in cache
            if (resultNatViewModel == null)
            {
                _logger.LogInformation("Table national all data is being retrieved from the database");

                var nationalResultLst = await _result.GetNational();

                //Because there is only currently national data for 2019 there should only be 1 result
                var nationalResult = nationalResultLst.First();

                //Convert national SchoolResult object to a TableViewModel object
                resultNatViewModel = nationalResult;

                //Save National TableViewModel data to cache
                await _cache.SaveNationalTableDataAll(resultNatViewModel);
            }


            var data = new { data = resultViewModel, national = resultNatViewModel };

            return Json(data);
        }


        [HttpPost]
        public async Task<IActionResult> GetResultsDisadvantaged()
        {
            _logger.LogInformation("Request made to get JSON object with data for Table All page");

            //Check if data is in cache
            var resultViewModel = await _cache.GetTableDataDisadvantaged();

            //Get results for all schools if data is not in cache
            if (resultViewModel.Count() == 0)
            {
                _logger.LogInformation("Table disadvantaged data is being retrieved from the database");

                //Get results for all schools 
                //where the percentage of disadvantaged pupils is not null
                var result = await _result.Get(
                    r => r.PTFSM6CLA1A != null,
                    r => r.OrderBy(s => s.School.SCHNAME),
                    r => r.School);

                //Converts from list of SchoolResult to List of TableViewModel
                resultViewModel = result.ConvertToTableViewModelDisadvantaged();

                //Save list of TableViewModel data to cache
                await _cache.SaveTableDataDisadvantaged(resultViewModel);

            }

            //Check if data is in cache
            var resultNatViewModel = await _cache.GetNationalTableDataDisadvantaged();

            //Get the national data from database if not in cache
            if (resultNatViewModel == null)
            {
                _logger.LogInformation("Table national disadvantaged data is being retrieved from the database");

                var nationalResultLst = await _result.GetNational();

                //Because there is only currently national data for 2019 there should only be 1 result
                var nationalResult = nationalResultLst.First();

                //Convert national SchoolResult object to a TableViewModel object
                resultNatViewModel = nationalResult;

                //Save National TableViewModel data to cache
                await _cache.SaveNationalTableDataDisadvantaged(resultNatViewModel);
            }


            var data = new { data = resultViewModel, national = resultNatViewModel };

            return Json(data);
        }



    }
}

SchoolPerformance/SchoolPerformance/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid mb-2">

                <h1 class="m-0 text-dark">About School Performance Dashboard</h1>

            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div>
                    This website was created in summer 2020 as part of my MSc Computer Science project.
                    The aim of the website is to help people gain a better of how schools perform
                    relative to the level of disadvantaged pupils a school has.
                    This site uses the 2019 results data that was obtained via the DfE performance tables website
                </div>

            </div>
        </div>
        <!-- /.content-body -->
    </div>

SchoolPerformance/SchoolPerformance/Views/Home/FAQ.cshtml
@{
    ViewData["Title"] = "FAQ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid mb-2">

                <h1 class="m-0 text-dark">Frequently Asked Questions</h1>

            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <!--- Question row-->
                <div class="row">
                    <div class="col-12">
                        <div class="card card-primary collapsed-card">
                            <!--- Card Header-->
                            <div class="card-header">
                                <h3 class="card-title">Where was the data used for this site obtained from?</h3>
                                <!--- Card Tools-->
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <!-- /.card-tools -->
                            </div>
                            <!-- /.card-header -->
                            <!--- Card Body-->
                            <div class="card-body">
                                This site uses the 2019 data from the DfE school performance tables.
                                Copies of the data can be downloaded from the DfE website by clicking
                                <a href="https://www.compare-school-performance.service.gov.uk/download-data">here</a>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.question row -->
                <!--- Question row-->
                <div class="row">
                    <div class="col-12">
                        <div class="card card-primary collapsed-card">
                            <!--- Card Header-->
                            <div class="card-header">
                                <h3 class="card-title">Which schools are included?</h3>
                                <!--- Card Tools-->
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <!-- /.card-tools -->
                            </div>
                            <!-- /.card-header -->
                            <!--- Card Body-->
                            <div class="card-body">
                                Any school in England that had a KS4 result in 2019 is included.
                                If a school did not have a KS4 result in 2019 they will not be included even if it is a secondary school
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.question row -->
                <!--- Question row-->
                <div class="row">
                    <div class="col-12">
                        <div class="card card-primary collapsed-card">
                            <!--- Card Header-->
                            <div class="card-header">
                                <h3 class="card-title">Why is the percentage of disadvantaged pupils at the end of KS4 used instead of the overall percentage of disadvantaged pupils?</h3>
                                <!--- Card Tools-->
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <!-- /.card-tools -->
                            </div>
                            <!-- /.card-header -->
                            <!--- Card Body-->
                            <div class="card-body">
                                This is because the files provided by the DfE only contains the percentage of disadvantaged pupils at the end of KS4 and not the overall percentage of disadvantaged pupils in each school
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.question row -->
                <!--- Question row-->
                <div class="row">
                    <div class="col-12">
                        <div class="card card-primary collapsed-card">
                            <!--- Card Header-->
                            <div class="card-header">
                                <h3 class="card-title">I have a school that had a KS4 result in 2019 but I cannot find the school in the Scatterplot</h3>
                                <!--- Card Tools-->
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <!-- /.card-tools -->
                            </div>
                            <!-- /.card-header -->
                            <!--- Card Body-->
                            <div class="card-body">
                                If a school had no disadvantaged pupils at the end of KS4 in 2019 
                                or a school have no data available for the percentage of disadvantaged pupils at the end of KS4 
                                they will not be included in the Scatterplot.
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.question row -->
                <!--- Question row-->
                <div class="row">
                    <div class="col-12">
                        <div class="card card-primary collapsed-card">
                            <!--- Card Header-->
                            <div class="card-header">
                                <h3 class="card-title">Can I export any of the data on this site</h3>
                                <!--- Card Tools-->
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <!-- /.card-tools -->
                            </div>
                            <!-- /.card-header -->
                            <!--- Card Body-->
                            <div class="card-body">
                                Both results tables can be exported to an excel or csv file. All you need to do is click the export button towards the top of the page
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.question row -->
                <!--- Question row-->
                <div class="row">
                    <div class="col-12">
                        <div class="card card-primary collapsed-card">
                            <!--- Card Header-->
                            <div class="card-header">
                                <h3 class="card-title">I only want to export some of the data on the table not all the data. How do I do this?</h3>
                                <!--- Card Tools-->
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <!-- /.card-tools -->
                            </div>
                            <!-- /.card-header -->
                            <!--- Card Body-->
                            <div class="card-body">
                                You can use the search functionality to filter the table and click the export filtered button to export only the schools in the filtered table
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.question row -->
                <!--- Question row-->
                <div class="row">
                    <div class="col-12">
                        <div class="card card-primary collapsed-card">
                            <!--- Card Header-->
                            <div class="card-header">
                                <h3 class="card-title">Can I search for schools in the tables by their DfE number of Unique Reference Number</h3>
                                <!--- Card Tools-->
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <!-- /.card-tools -->
                            </div>
                            <!-- /.card-header -->
                            <!--- Card Body-->
                            <div class="card-body">
                                Yes you can use the search box to filter schools by the DfE number of Unique Reference Number
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.question row -->

            </div>
        </div>
        <!-- /.content-body -->
    </div>

SchoolPerformance/SchoolPerformance/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "School Performance Homepage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">

    <!-- Header -->
    <div class="content-header">

        <div class="container-fluid">

            <div class="jumbotron jumbotron-home jumbotron-fluid">

                <div class="container">

                    <!-- Header Title-->
                    <div class="d-flex text-header text-dark text-center justify-content-center">School Performance Dashboard</div>

                    <!-- Dashed line-->
                    <hr class="style1">

                    <!-- Header Text-->
                    <div class="lead d-flex text-center justify-content-center">
                        This dashboard allows you to view 2019 examination results for all schools in England
                        with an emphasis on the percentage of disadvantaged pupils at each school
                        and the performance of disadvantaged pupils at each school
                    </div>

                </div>

            </div>

        </div>

    </div>
    <!-- /.header -->
    <!-- Main content -->
    <div class="content">

        <div class="container-fluid">

            <!--Row -->
            <div class="row justify-content-center">

                <!--Card (View All Results) -->
                <div class="col-sm-6">
                    <div class="card bg-primary">
                        <div class="card-header">
                            <h5 class="m-0">View All Schools Results</h5>
                        </div>
                        <div class="card-body">
                            <p>
                                <a asp-controller="Scatterplot" asp-action="Index" id="scatterplot-home-link"
                                   class="card-link text-light">View Result Scatterplot for all schools in England</a>
                            </p>
                            <p>
                                <a asp-controller="Tables" asp-action="Index" id="results-all-home-link"
                                   class="card-link text-light">View Result Table for all schools in England</a>
                            </p>
                            <p>
                                <a asp-controller="Tables" asp-action="Disadvantaged" id="results-disadvantaged-home-link"
                                   class="card-link text-light">View Disadvantaged Result Table for all schools in England</a>
                            </p>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
                <!--Card (Search School) -->
                <div class="col-sm-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h5 class="m-0">Search Individual School Result</h5>
                        </div>
                        <div class="card-body">
                            <p class="card-text">Search School by Unique Reference Number (URN), School Name or DfE Number</p>
                            <form asp-controller="School" asp-action="School" method="post">
                                <div class="input-group">
                                    <input type="text" class="form-control school-search" id="homepage-search" autocomplete="off" name="id">
                                    <span class="input-group-append">
                                        <button type="submit" class="btn btn-primary" id="homepage-search-btn">
                                            <i class="fas fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.row -->

        </div>

    </div>
    <!-- /.content -->

</div>